name: CodeCov
on: [push]
 
jobs:
  build:
    name: Run Python Tests
    runs-on: ubuntu-latest
 
    steps:
 
    - uses: actions/checkout@v2
 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
 
    - name: Install Python dependencies
      run: |
        sudo apt install -y hdf5-tools
        $CONDA/bin/conda install -c conda-forge mamba
        $CONDA/bin/mamba env update --file pytest_env.yml --name base
        $CONDA/bin/mamba develop .
 
    - name: Test with pytest
      run: |
        $CONDA/bin/pytest --cov=. --cov-report xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage1.xml,./coverage2.xml
        flags: unittests
        name: codecov-umbrella
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
